Fix cache support for some versions
arangodb/rta-makedata pull request #14
Opened 2023-05-08 12:15 UTC by alexbakharew

### Scope & Purpose

*(Please describe the changes in this PR for reviewers, motivation, rationale - **mandatory**)*

- [ ] :hankey: Bugfix
- [ ] :pizza: New feature
- [ ] :fire: Performance improvement
- [ ] :hammer: Refactoring/simplification

### Checklist

- [ ] sidelining PRs
  - [ ] [ArangoDB Pullrequest](https://github.com/arangodb/arangodb/pull/)
  - [ ] [RTA Pullrequest](https://github.com/arangodb/release-test-automation/pull)

2023-05-10 13:17 UTC, dothebart requested changes
please fix the two version checks

2023-05-11 09:40 UTC, alexbakharew commented on test_data/makedata_suites/402_views.js
> +    if (semver.lt(version, "3.9.11") || semver.lt(version, "3.10.6")) {
Resolved

2023-05-11 10:09 UTC, alexbakharew commented
Fix for https://arangodb.atlassian.net/browse/BTS-1352 will be introduced later

2023-05-11 12:14 UTC, dothebart approved these changes

2023-05-11 12:14 UTC, dothebart commented
great, tnx!

2023-05-12 09:09 UTC, merged